project:
  type: website
  output-dir: docs/

website:
  title: "Farpoint Folio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tstoeter
format:
  html:
    theme: default
    css: styles.css
